Adapt Rust's RFC process for Sway
FuelLabs/sway-rfcs pull request #1
Opened 2022-06-15 16:05 UTC by sezna

This is an adaption of Rust's RFC process for Sway. I've _slightly_ modified the template, readme, and initial RFC to describe the RFC process itself here.

2022-06-15 20:44 UTC, mohammadfawaz reviewed
Looks good! Just some minor nits.

2022-06-15 20:44 UTC, mohammadfawaz commented on rfcs/0001-rfc-process.md
> +community and the [core team].
```suggestion
through a bit of a design process and produce a consensus among the Sway
community and the [core team].
```
This was just causing some weird formatting issues in the preview.

2022-06-15 20:44 UTC, mohammadfawaz commented on rfcs/0001-rfc-process.md
> +* Create a corresponding issue on [Sway repo](https://github.com/FuelLabs/sway)
```suggestion
* Create a corresponding issue on [Sway repo](https://github.com/FuelLabs/sway).
```

2022-06-15 20:44 UTC, mohammadfawaz commented on rfcs/0001-rfc-process.md
> +* Add an entry in the [Active RFC List] of the root `README.md`.
Might as well add this (empty) list already in the `README.md` as part of this PR?

2022-06-15 20:44 UTC, mohammadfawaz commented on rfcs/0001-rfc-process.md
> +* Fork the RFC repo https://github.com/FuelLabs/sway-rfcs (or make a branch if you are core-team)
```suggestion
* Fork the RFC repo https://github.com/FuelLabs/sway-rfcs (or make a branch if you are core-team).
```

2022-06-15 20:44 UTC, mohammadfawaz commented on rfcs/0001-rfc-process.md
> +* Fill in the RFC
```suggestion
* Fill in the RFC.
```

2022-06-16 01:10 UTC, mitchmindtree reviewed
Nice one @sezna, looking really good!

This will also be a great place to point folk who want to see certain features/changes in Sway as it provides some structure on how to propose them in a useful manner.

Would give the tick, but will defer to @mohammadfawaz after addressing his last suggestion.

2022-06-16 01:53 UTC, adlerjohn commented on rfcs/0001-rfc-process.md
> +Rust's RFC process has proven efficiency that we'd like to emulate._
This doesn't italicize the block.

2022-06-16 01:53 UTC, adlerjohn commented on rfcs/0001-rfc-process.md
> +   - Additions only likely to be _noticed by_ other developers-of-sway,
I know the Rust version says `users-of-rust` lowercase, but that seems wrong.
```suggestion
   - Additions only likely to be _noticed by_ other developers-of-Sway,
```

2022-06-16 17:34 UTC, mohammadfawaz approved these changes
Looks good!

2022-06-16 17:35 UTC, adlerjohn approved these changes
utACK

2022-06-16 17:36 UTC, emilyaherbert commented
I was OOO yesterday, can you hold off merging until I've had a chance to review?

2022-06-28 17:15 UTC, emilyaherbert requested changes
Maybe I missed it, but I didn't see anything specific about RFC's that propose breaking changes. It might be worthwhile to make a note requesting that any such RFC's describe the implications of the breaking change (i.e. if there is some syntax that changes, that change will need to be propagated to the standard library)

2022-06-28 17:33 UTC, sezna commented
Does [this section](https://github.com/FuelLabs/sway-rfcs/pull/1/files#diff-9ae0eaba1ea4e62706bea031447886b41a1a9f14b132937f4fd801e9a8148042R29) cover what you're referring to? In Rust RFCs, this is typically where things like stdlib implementations are discussed [example](https://rust-lang.github.io/rfcs/3058-try-trait-v2.html#standard-implementations)

Additionally, breaking-ness is usually covered in the drawbacks or implementation details section. [example](https://rust-lang.github.io/rfcs/1212-line-endings.html#drawbacks). 

Are you proposing a specific section regarding addressing if anything is breaking, after all the other sections? I think that's definitely reasonable

2022-06-28 17:44 UTC, merged