RFC for const generics
FuelLabs/sway-rfcs pull request #42
Opened 2024-10-27 13:20 UTC by xunilrj

2024-12-06 16:01 UTC, IGI-111 commented on README.md
> +| [0014](rfcs/0014-const-generics.md)       | Const Generics       |
Looks like I failed to update the list for the ABI errors one, Const generics should be number 15 actually.

2025-01-21 11:41 UTC, xunilrj commented on README.md
> +| [0014](rfcs/0014-const-generics.md)       | Const Generics       |
Done.

2025-01-24 18:45 UTC, IGI-111 approved these changes
LGTM, the definition itself ends up pretty straightforward, the hard part is going to be the monomorphization implementation.

2025-01-29 23:09 UTC, JoshuaBatty approved these changes

2025-01-30 13:45 UTC, ironcev requested changes

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +This new syntax has three forms: declarations, instantiations and references.
```suggestion
This new syntax has three forms: declarations, instantiations, and references.
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +"const generics declarations" can appear anywhere all other generic arguments declarations are valid:
```suggestion
"Const generics declarations" can appear anywhere all other generic arguments declarations are valid:
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +fn id<const N: usize>(...) { ... }
```suggestion
fn id<const N: u64>(...) { ... }
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +struct SpecialArray<const N: usize> {
```suggestion
struct SpecialArray<const N: u64> {
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +impl<const N: usize> AbiEncode for str[N] {
```suggestion
impl<const N: u64> AbiEncode for str[N] {
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +"const generics instantiations" can appear anywhere all other generic argument instantiations are valid:
```suggestion
"Const generics instantiations" can appear anywhere all other generic argument instantiations are valid:
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +"const generics references" can appear anywhere any other identifier appears. For semantic purposes, there is no difference between the reference of a "const generics" and a "normal" const.
```suggestion
"Const generics references" can appear anywhere any other identifier appears. For semantic purposes, there is no difference between the reference of a "const generics" and a "normal" const.
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +fn f<const I: usize>() {
```suggestion
fn f<const I: u32>() {
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +fn f<const I: usize>() where I > 10 {
```suggestion
fn f<const I: u8>() where I > 10 {
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +fn f<const I: usize>() -> Vec<I> {
```suggestion
fn f<const I: u64>() -> Vec<I> {
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +fn f<const I: usize>() where I > 10 {
Supporting constraints can be added to future possibilities. One case I see as interesting, is ensuring that an array size is greater then zero. Or for small vec implementations to ensure the upper bound is not to high.

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +In the example above, `f` only is available when the generic argument of `SomeStruct` is known to be `bool`. This will not be supported for "const generics", which means that the example below will n
```suggestion
In the example above, `f` is only available when the generic argument of `SomeStruct` is known to be `bool`. This will not be supported for "const generics", which means that the example below will not be supported:
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +impl SomeBoolStruct<false> {
As mentioned, we should explicitly specify which types are supported. Out of this example with `bool` I assume all uint types + `bool` will be supported. I don't see a reason not to.

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +Prevention of code bloat will be the responsability of the optimizer.
```suggestion
Prevention of code bloat will be the responsibility of the optimizer.
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +Monomorphization for const generics has one extra complexity to support arbitrary expressions it is needed to "solve" an equation. For example,
```suggestion
Monomorphization for const generics has one extra complexity. To support arbitrary expressions it is needed to "solve" an equation. For example,
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +if a variable is typed as `[u64; 1]` and a method with its `self` type as `[u64; N + 1]` is called, the monomorphization process needs to know that `N` needs to be valued as `0` and if the variable i
```suggestion
if a variable is typed as `[u64; 1]` and a method with its `Self` type as `[u64; N + 1]` is called, the monomorphization process needs to know that `N` needs to be valued as `0` and if the variable is `[u64; 2]`, `N` will be `1`.
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +fn bigger<const N: usize>(a: [u64; N]) -> [u64; N + 1] {
```suggestion
fn bigger<const N: u64>(a: [u64; N]) -> [u64; N + 1] {
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +This poses the challenge of having an expression tree inside the type system. Currently `sway` already
```suggestion
This poses the challenge of having an expression tree inside of the type system. Currently Sway already 
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +and  last one is only create after some `TypeInfo` already exist, and thus cannot be used.
```suggestion
and the last one is only created after some `TypeInfo` already exists, and thus cannot be used.
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +At the same time, the parser should be able to parse any expression and return a friendly error that such expression,
```suggestion
At the same time, the parser should be able to parse any expression and return a friendly error that such expression
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +So, in case of a unsupported expression the parser will parser the `const generic` expression as it does for normal `Expr`and will lower it to the type system expression enum, but in the place of the
```suggestion
So, in case of an unsupported expression the parser will parser the `const generic` expression as it does for normal `Expr`and will lower it to the type system expression enum, but in the place of the unsupported expression will return a `TypeInfo::ErrorRecovery`.
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +These expressions will also increase the complexity of all types related algorithms such as:
```suggestion
These expressions will also increase the complexity of all type related algorithms such as:
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +More research is needed to understand if this change can potentially change the semantics of any program written in `sway`.
```suggestion
More research is needed to understand if this change can potentially change the semantics of any program written in Sway.
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +
Perhaps to explicitly mention that the insertion into trait map must already search for conflicting implementations in regard to const generic arguments. 
```suggestion
When inserting into the `TraitMap` the search for duplicated definitions will need to be extended for const generic arguments. E.g.:
```sway
struct S<const N:u8> { }

impl<const N:u8> S<N> {
    fn a(&self) { }
}

impl S<0> {
    fn a(&self) { } // <<<--- ERROR: Conflicting definition.
    fn b(&self) { } // <<<--- OK.
}

trait Trait { }

impl<const N:u64> Trait for [u8;N] { }

impl Trait for [u8;2] { } <<<--- ERROR: Conflicting implementation.
``` 
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +1. Creation of the feature flag `const-generics`;
```suggestion
1. Creation of the feature flag `const_generics`;
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +fn f<const I: usize>() { __log(I); }
```suggestion
fn f<const I: u8>() { __log(I); }
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +impl<T, const N: usize> AbiEncode for [T; N] { ... }
```suggestion
impl<T, const N: u64> AbiEncode for [T; N] { ... }
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +4. Being able to `encode` arrays of any size;
```suggestion
4. Being able to `abi_encode` arrays of any size;
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +5. Inference of the example above
```suggestion
5. Inference of the example above;
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +6. Struct/enum support for const generics
```suggestion
6. Struct/enum support for const generics;
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +8. `impl` declarations.
```suggestion
8. `impl` declarations;
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +9. Function/method reference;
```suggestion
9. Function/method reference.
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +This RFC is partially based on Rust's own const generic system: https://doc.rust-lang.org/reference/items/generics.html#const-generics, https://blog.rust-lang.org/inside-rust/2021/09/06/Splitting-con
```suggestion
This RFC is partially based on Rust's own const generic system:
- https://doc.rust-lang.org/reference/items/generics.html#const-generics
- https://blog.rust-lang.org/inside-rust/2021/09/06/Splitting-const-generics.html
- https://rust-lang.github.io/rfcs/2000-const-generics.html
- https://doc.rust-lang.org/beta/unstable-book/language-features/generic-const-exprs.html
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +1. What is the impact of changing the "method called algorithm"?
```suggestion
1. What is the impact of changing the "method call search algorithm"?
```

2025-01-30 13:45 UTC, ironcev commented on rfcs/0015-const-generics.md
> +# Future possibilities
As mentioned above, implementing constraints like `where N > 0`.

2025-03-20 17:13 UTC, xunilrj commented on rfcs/0015-const-generics.md
> +impl SomeBoolStruct<false> {
The idea of this part, is to inform that specialization will not be supported for "const generics". The "type specialization" is just an example, and it already exists in Sway.

2025-03-20 17:17 UTC, xunilrj commented on rfcs/0015-const-generics.md
> +
> impl S<0> {

This specialization will not be supported.

2025-03-31 10:42 UTC, ironcev approved these changes

2025-04-04 10:14 UTC, vaivaswatha approved these changes

2025-04-04 11:11 UTC, merged